name: 'dbt_praticas'
version: '1.0.0'

profile: 'dbt_praticas'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

models:
  dbt_praticas:

    staging:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      +materialized: table
